# Generated by Django 4.0.4 on 2022-06-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city_master',
            fields=[
                ('CTID', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('alternative', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.city_master')),
            ],
        ),
        migrations.CreateModel(
            name='emp_role',
            fields=[
                ('emp_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='role_master',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('active_status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_master',
            fields=[
                ('SID', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='technology_master',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('active_status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('estimate_date', models.DateField(blank=True, null=True)),
                ('est_end_date', models.DateField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('employee_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.emp_role')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField()),
                ('alternate', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('r_address', models.CharField(max_length=100, null=True)),
                ('p_address', models.CharField(max_length=100, null=True)),
                ('join_date', models.DateField(null=True)),
                ('emp_status', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('p_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_city', to='smart_app.city_master')),
                ('p_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_state', to='smart_app.state_master')),
                ('r_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_city', to='smart_app.city_master')),
                ('r_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_state', to='smart_app.state_master')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emp_tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.employee')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.technology_master')),
            ],
        ),
        migrations.AddField(
            model_name='emp_role',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.employee'),
        ),
        migrations.AddField(
            model_name='emp_role',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.role_master'),
        ),
        migrations.AddField(
            model_name='client',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.state_master'),
        ),
        migrations.AddField(
            model_name='city_master',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.state_master'),
        ),
    ]
