# Generated by Django 4.0.4 on 2022-06-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_emp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.employee')),
            ],
        ),
    ]
