# Generated by Django 4.0.4 on 2022-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0007_remove_emp_role_role_id_emp_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_role',
            name='role_id',
            field=models.ManyToManyField(related_name='emp_rol', to='smart_app.role_master'),
        ),
    ]
