# Generated by Django 4.0.4 on 2022-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0008_alter_emp_role_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='employee_role_id',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='employee_role_id',
            field=models.ManyToManyField(to='smart_app.emp_role'),
        ),
    ]
