# Generated by Django 4.0.4 on 2022-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0009_remove_projectteam_employee_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_emp',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
