# Generated by Django 4.0.4 on 2022-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0010_alter_login_emp_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_emp',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
