# Generated by Django 4.0.4 on 2022-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0012_remove_emp_role_role_id_emp_role_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_role',
            name='role_id',
        ),
        migrations.AddField(
            model_name='emp_role',
            name='role_id',
            field=models.ManyToManyField(related_name='emp_rol', to='smart_app.role_master'),
        ),
    ]
