# Generated by Django 4.0.4 on 2022-06-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0014_remove_emp_role_role_id_emp_role_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='employee_role_id',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='employee_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.emp_role'),
        ),
    ]
