# Generated by Django 4.0.5 on 2022-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0015_remove_projectteam_employee_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_role',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_tech',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='login_emp',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
