# Generated by Django 4.0.5 on 2022-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0016_alter_client_active_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_emp',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
