# Generated by Django 4.0.5 on 2022-06-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0017_alter_login_emp_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_emp',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.employee'),
        ),
    ]
