# Generated by Django 4.0.5 on 2022-07-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0021_project_proj_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED')], default='ACTIVE', max_length=9, null=True),
        ),
    ]
